name: My Action
inputs:
  repoName:
    description: 'Name of the Github repo including the org/user name'
    required: true
  manifestName:
    description: 'Name of the manifest to deploy. Should be listed in .pi-app-updater.yaml'
    required: true
  host:
    description: 'Host containing protocol for the Pi App Deployer'
    required: true
  artifactName:
    description: 'Name of the artifact uploaded from the workflow'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - deploy
    - --repoName
    - ${{ inputs.repoName }}
    - --manifestName
    - ${{ inputs.manifestName }}
    - --host
    - ${{ inputs.host }}
    - --artifactName
    - ${{ inputs.artifactName }}
