name: My Action
inputs:
  repoName:
    description: 'Name of the Github repo including the org/user name'
    required: true
  manifestName:
    description: 'Name of the manifest to deploy. Should be listed in .pi-app-updater.yaml'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --repoName
    - ${{ inputs.repoName }}
    - --manifestName
    - ${{ inputs.manifestName }}
